services:
  - type: web
    name: telegram-cleaner-bot-no-yaml
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
